### ISSUE TITLE
How to generate atlas mask?

### ISSUE THREAD

**Issue by John1231983** [JanaLipkova/s3#1]
Thanks for sharing it. I have a question about atlas mask. It mentioned that
>atlas_mask = binary mask of the atlas brain, the mask was created as a sum of segmented atlas anatomies

However, I opened it and it does not look likes probability map. Because different subject has different size of brain mask, so I expected the output must be a smooth probability. In my opinion, the mask that you gave us likes mask of a subject instead of a combination of multiple subjects

If I have ten raw image and its brain mask. Do you know how to create probability brain mask?

**Comment by JanaLipkova** [comment]
Hi John,

than you for the question. The atlas mask is a single probabilistic mask created from multiple subjects subjects. But the atlas has been constructed beforehand (see the link to the used atlas in the s3 description). So it is a single mask, but it is probabilistic because its has smooth values between 0-1, compared to binary 0,1. 
If you are interested in creating probabilistic mask from your existing mask, please refer to any paper describing brain atlas construction, like the atlas referred to in the main s3 description. 
I hope it helped.
